# Generated by Django 4.1.3 on 2022-12-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_gender_profile_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='mobile_no',
            new_name='mobile_no2',
        ),
    ]
