# Generated by Django 4.1.4 on 2022-12-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_mobile_no_address_mobile_no2'),
        ('accounts', '0004_rename_mobile_no_address_mobile_no2_and_more'),
    ]

    operations = [
    ]
